#+TITLE: tmux config
#+AUTHOR: Jamsjz
#+auto_tangle: t

* Tmux Configuration

This configuration file customizes tmux to enhance your terminal multiplexer experience. The following sections contain code blocks that will be tangled to `~/.tmux.conf`.
** Kill Session

#+begin_src conf :tangle .tmux.conf
bind -n M-P kill-session
bind -n M-T kill-server
#+end_src
** Switch sessions
#+begin_src conf :tangle .tmux.conf
bind -n M-1 switch-client -t home
bind -n M-2 switch-client -t config
bind -n M-3 switch-client -t py
bind -n M-4 switch-client -t dsc
bind -n M-5 switch-client -t install
#+end_src
** Split Panes

These keybindings allow you to split the tmux panes horizontally and vertically using `|` and `-`.

#+begin_src conf :tangle .tmux.conf
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
#+end_src

** Reload Configuration

This keybinding reloads the tmux configuration file.

#+begin_src conf :tangle .tmux.conf
bind r source-file ~/.tmux.conf
#+end_src

** Vim-Tmux Pane Navigator

These keybindings enable navigation between tmux panes and Vim splits seamlessly.

#+begin_src conf :tangle .tmux.conf
set -g @plugin 'christoomey/vim-tmux-navigator'
#+end_src

** Enable Mouse Control

Enable mouse support for clickable windows, panes, and resizable panes.

#+begin_src conf :tangle .tmux.conf
set -g mouse on
#+end_src

** Window and Pane Behavior

Prevent automatic renaming of windows and open new windows in the current path.

#+begin_src conf :tangle .tmux.conf
set-option -g allow-rename off
bind c new-window -c "#{pane_current_path}"
unbind '"'
unbind %
#+end_src

** Pane Resizing

Keybindings to resize panes using `j`, `k`, `l`, and `h`.

#+begin_src conf :tangle .tmux.conf
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z
#+end_src

** Vi Mode Keys

Enable vi-style keybindings in tmux copy mode.

#+begin_src conf :tangle .tmux.conf
set-window-option -g mode-keys vi
set-option -g set-clipboard on
#+end_src

** Terminal Colors

Set default terminal to 256 colors for better color support.

#+begin_src conf :tangle .tmux.conf
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
#+end_src

** URL Handling

Capture visible pane content and open URLs using `urlview`.

#+begin_src conf :tangle .tmux.conf
bind u capture-pane \; save-buffer /tmp/tmux-buffer \; split-window -l 10 "urlview /tmp/tmux-buffer"
#+end_src

** Shell Settings

Change the default shell to fish and set escape time to zero.

#+begin_src conf :tangle .tmux.conf
set-option -g default-shell "/usr/bin/fish"
set -sg escape-time 0
#+end_src

** Control Backspace

Enable xterm key handling for better backspace control.

#+begin_src conf :tangle .tmux.conf
set -wg xterm-keys on
set -sg extended-keys always
set -as terminal-features 'xterm*:extkeys'
set -g allow-passthrough on
set -gq allow-passthrough on
#+end_src

** Window Navigation

Keybindings for navigating between windows using `M-C-n` and `M-C-p`.

#+begin_src conf :tangle .tmux.conf
bind -n M-C-n next-window
bind -n M-C-p previous-window
#+end_src

** Renumber Windows

Renumber windows when one is closed.

#+begin_src conf :tangle .tmux.conf
set -g renumber-windows on
#+end_src

** fzf-url Settings

Configure fzf-url for opening URLs.

#+begin_src conf :tangle .tmux.conf
set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'
#+end_src

** Design Tweaks

Disable visual bell and set styles for various tmux elements.

#+begin_src conf :tangle .tmux.conf
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

setw -g clock-mode-colour colour1
setw -g mode-style 'fg=colour1 bg=colour18 bold'
set -g pane-border-style 'fg=colour1'
set -g pane-active-border-style 'fg=colour3'

set -g status-position top
set -g status-justify left
set -g status-style 'fg=colour1'
set -g status-left ''
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50
set -g status-left-length 10

setw -g window-status-current-style 'fg=colour0 bg=colour1 bold'
setw -g window-status-current-format ' #I #W #F '
setw -g window-status-style 'fg=colour1 dim'
setw -g window-status-format ' #I #[fg=colour7]#W #[fg=colour1]#F '
setw -g window-status-bell-style 'fg=colour2 bg=colour1 bold'

set -g message-style 'fg=colour2 bg=colour0 bold'
#+end_src

** Gruvbox Theme

Configure the Gruvbox theme for tmux.

#+begin_src conf :tangle .tmux.conf
## Gruvbox Theme
# set -g @plugin 'z3z1ma/tmux-gruvbox'
# set -g @gruvbox_window_left_separator "█"
# set -g @gruvbox_window_middle_separator "█"
# set -g @tmux-gruvbox 'dark'
# set -g @gruvbox_window_right_separator "█"
# set -g @gruvbox_window_number_position "left"
# set -g @gruvbox_window_status_icon_enable "yes"
# set -g @gruvbox_window_status_enable "yes"
# set -g @gruvbox_icon_window_last "󰖰"
# set -g @gruvbox_window_default_fill "number"
# set -g @gruvbox_status_left_separator ""
# set -g @gruvbox_status_right_separator "█"
# set -g @gruvbox_status_right_separator_inverse "no"
# set -g @gruvbox_status_fill "icon"
# set -g @gruvbox_status_modules_right "application session"
# set -g @gruvbox_status_modules_left ""
# set -g @gruvbox_icon_window_current "󰖯"
# set -g @gruvbox_status_connect_separator "yes"
# set -g @gruvbox_icon_window_zoom "󰁌"
# set -g @gruvbox_icon_window_mark "󰃀"
# set -g @gruvbox_icon_window_silent "󰂛"
# set -g @gruvbox_icon_window_activity "󰖲"
# set -g @gruvbox_icon_window_bell "󰂞"

# One Dark Theme

set -g @plugin 'odedlaz/tmux-onedark-theme'
#+end_src

** Floax Plugin

Configure the Floax plugin for tmux.

#+begin_src conf :tangle .tmux.conf
set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-bind 'p'
set -g @floax-change-path 'false'
#+end_src

** Sessionx Plugin

Configure the Sessionx plugin for tmux.

#+begin_src conf :tangle .tmux.conf
set -g @sessionx-auto-accept 'off'
set -g @sessionx-bind 'o'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-custom-paths-subdirectories 'false'
set -g @sessionx-filter-current 'false'
#+end_src

** Continuum and Resurrect

Enable Continuum and Resurrect plugins to restore tmux sessions.

#+begin_src conf :tangle .tmux.conf
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'
#+end_src

** Plugins

Install various useful tmux plugins.

#+begin_src conf :tangle .tmux.conf
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'omerxx/tmux-floax'

# TPM initialization
run '~/.tmux/plugins/tpm/tpm'
#+end_src

* Keybindings

This table lists all the custom keybindings configured in the tmux configuration file.

| Keybinding    | Description                     |
|---------------+---------------------------------|
| bind          | Split pane horizontally         |
| bind -        | Split pane vertically           |
| bind r        | Reload config file              |
| bind -n C-h   | Navigate left pane              |
| bind -n C-j   | Navigate down pane              |
| bind -n C-k   | Navigate up pane                |
| bind -n C-l   | Navigate right pane             |
| bind c        | Open new window in current path |
| bind -r j     | Resize pane down by 5           |
| bind -r k     | Resize pane up by 5             |
| bind -r l     | Resize pane right by 5          |
| bind -r h     | Resize pane left by 5           |
| bind -r m     | Toggle pane zoom                |
| bind u        | Capture pane and open URL view  |
| bind -n M-C-n | Next window                     |
| bind -n M-C-p | Previous window                 |
| m-k m-Shift-k | kill sessions                   |
| m-12345       | switch sessions                 |

